### ISSUE TITLE
Items duplicates when added second time

### ISSUE THREAD

**Issue by vadimleonov** [maxep/MXParallaxHeader#105]
How to correctly reasign `tableView.parallaxHeader.view` ?

I have a problem when I trying to reassign, it always duplicates views:

```
tableView.parallaxHeader.view = customView
tableView.parallaxHeader.view = customView1
tableView.parallaxHeader.view = customView2
```

![image](https://user-images.githubusercontent.com/35032429/55807875-a2ffd380-5aeb-11e9-914e-4c39ad1d4900.png)

**Comment by shapeofnoise** [comment]
The same problem: https://github.com/maxep/MXParallaxHeader/issues/102
You have to manually remove old view from superview before adding a new one, at least until they fix it. From the code it looks just like a bug.

**Comment by maxep** [comment]
Has been fixed :)
