### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by 0fcourse** [maxep/MXParallaxHeader#108]
I'm getting the warning emails from Apple every time we submit new version to App Store Connect.
As my app not using any UIWebView and I looked at the problem, and it turns out that MXParallaxHeader using UIWebView in "MXWebViewController.m" file.

Apple warning:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

could you please have a look at this issue.

Thanks.

**Comment by Kedar-27** [comment]
Yes, this issue must be fixed asap @maxep

**Comment by maxep** [comment]
__`MXWebViewController` is from the examples it shouldn't be part of your app.__

UIWebView is not part of MXParallaxHeader and refs to UIWebView have been removed from the examples a while ago.
