### ISSUE TITLE
How can I set header view height & minimum height with programmatically

### ISSUE THREAD

**Issue by hkim777** [maxep/MXParallaxHeader#109]
Hi..

I want to use MXParallaxHeader with using Controller.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        self.headerViewController = DvChannelMainViewHeaderController()
        
        headerViewController?.parallaxHeader?.height = 300
        headerViewController?.parallaxHeader?.minimumHeight = 250
        
        
        
        self.childViewController = DvChannelMainViewContentsViewController()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

this is not work properly..

I just tried with 

        parallaxHeader?.height = 300
        parallaxHeader?.minimumHeight = 100
        
or

        self.scrollView.parallaxHeader.height = 300
        self.scrollView.parallaxHeader.minimumHeight = 250
 
 but not work also.

how can I setting height and minimum height with programmatically?

Thx

**Comment by Zeeshan0075** [comment]
I'm also facing this problem their's no way out for this problem... Unfortunately !!!

**Comment by New-tap** [comment]
I put it in viewDidAppear and it worked

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    if (_isFirstSet) {
        _isFirstSet = NO;
        self.scrollView.parallaxHeader.minimumHeight = self.scrollView.parallaxHeader.minimumHeight + self.topLayoutGuide.length;
        self.scrollView.parallaxHeader.height = self.scrollView.parallaxHeader.height + self.topLayoutGuide.length;
    }
}
