### ISSUE TITLE
Weird width on MXParallaxHeader 1.1.0

### ISSUE THREAD

**Issue by vkcldhkd** [maxep/MXParallaxHeader#114]
#### Issue Description
* Weird width on MXParallaxHeader 1.1.0

#### Environment Information
* MXParallaxHeader 1.1.0
* iPhone7 11.3.1, iPhone XR 13.2.2
* Xcode 11.2.1

#### Your Code

```
let height: CGFloat = Constants.APPDELEGATE.cellSize.height + 50 + UIWindow.safeAreaTopInset

    override func viewDidLoad() {
        super.viewDidLoad()

        detailTableView.contentInsetAdjustmentBehavior = .never
        headerView = PostDetailCardView()
        detailTableView.parallaxHeader.view = headerView
        detailTableView.parallaxHeader.height = height
        detailTableView.parallaxHeader.mode = .fill
        detailTableView.parallaxHeader.minimumHeight = 0
}
```

#### Screenshot
![IMG_0058](https://user-images.githubusercontent.com/6158125/69116927-56dd2e80-0ad1-11ea-9861-12277ffda16c.PNG)
by MXParallaxHeader 0.6.1

![IMG_0059](https://user-images.githubusercontent.com/6158125/69116937-60ff2d00-0ad1-11ea-8269-726b607ce3dc.PNG)
by MXParallaxHeader 1.1.0

**Comment by macoapps** [comment]
Same issue here :(

**Comment by alflix** [comment]
as for me, add width constraint of your headerView  cant fix this issue

**Comment by iOSDevFin** [comment]
I have the same issue

**Comment by Nahatakyan** [comment]
I have the same issue. I fixed it like this.

```
tableViewHeaderView = TableHeader(frame: view.bounds)
tableViewHeaderView.translatesAutoresizingMaskIntoConstraints = false

tableView.parallaxHeader.view = tableViewHeaderView
tableView.parallaxHeader.height = view.frame.height * 0.6
tableView.parallaxHeader.mode = .fill
tableView.parallaxHeader.minimumHeight = 0

tableViewHeaderView.widthAnchor.constraint(equalTo: tableView.widthAnchor).isActive = true
```

**Comment by macoapps** [comment]
Nice fix, it works perfectly for me !

**Comment by Harshvk** [comment]
Getting the same issue. The above-mentioned solution is also not working when header is instantiated from the nib.

**Comment by RaheelCr7** [comment]
Scroll not working after I am adding width constraint!
please help

**Comment by SandsHellCreations** [comment]
Above solutions didn't work same error
<img width="457" alt="Screenshot 2020-05-15 at 3 30 06 PM" src="https://user-images.githubusercontent.com/25215789/82038297-f6662d00-96c0-11ea-9e9d-497430d63435.png">

**Comment by SandsHellCreations** [comment]
Issue is in your latest version of pod 
0.6.1 this release version of your code working fine

**Comment by MohdElBasyouni** [comment]
Same problem here and thanks to @Nahatakyan , below code fix it;

> tableViewHeaderView.translatesAutoresizingMaskIntoConstraints = false
> tableViewHeaderView.widthAnchor.constraint(equalTo: tableView.widthAnchor).isActive

**Comment by moquiutijunio** [comment]
I solved this problem fixing width in my header view!
