### ISSUE TITLE
Keyboard appearance

### ISSUE THREAD

**Issue by gumenuk39** [maxep/MXParallaxHeader#117]
I've added to example UITextfield
I scroll to hide header, then textfield becomes first responder
Wired behaviour: scrollview scrolls back. 

![2019-12-20134024](https://user-images.githubusercontent.com/14789735/71252737-719ffe80-232e-11ea-80dc-0bb7881baf64.gif)

**Comment by choiks14** [comment]
same here

**Comment by dariopellegrini** [comment]
Same here

**Comment by amrit42087** [comment]
I am facing the same issue
