### ISSUE TITLE
The bottom of view in Scrollview is not fully displayed.

### ISSUE THREAD

**Issue by mkjwa** [maxep/MXParallaxHeader#119]
When minimumHeight  is not 0, contents view's bottom not displayed reaching the bottom by scrolling. 

#### Issue Description
When minimumHeight  is not 0, contents view's bottom not displayed reaching the bottom by scrolling. 

* parallaxHeader.minimumHeight set to value more than 0.

#### Environment Information
* MXParallaxHeader Current Version
* iOS 13.3 

#### Your Code
Iin MXScrollViewExample,
```
  scrollView.parallaxHeader.view = headerView  
  scrollView.parallaxHeader.height = 300
  scrollView.parallaxHeader.mode = .fill
  scrollView.parallaxHeader.minimumHeight = 200
```

![IMG_2177](https://user-images.githubusercontent.com/38811379/73514370-d0c85700-4434-11ea-8066-7e97dcdc8d97.PNG)

**Comment by cynical1031** [comment]
Not sure, but try this 

tableView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: scrollView.parallaxHeader.minimumHeight, right: 0);
