### ISSUE TITLE
Pan gesture of MXScrollView conflicts with UITableview didSelect gesture 

### ISSUE THREAD

**Issue by mavericksunny** [maxep/MXParallaxHeader#14]
I have added a UITableView as a subview of MXScrollView and encountered the issue that the Pan gesture of MXScrollView conflicts with UITableview didSelect gesture 
This happens if I scroll the view partially and try to tap on a UITableViewCell, the tap is not detected for the first time, it works for the second tap.

**Comment by alezoffoli** [comment]
Exactly the same for me. Any thoughts on that?

---

Setting panGestureRecognizer.cancelsTouchesInView = false on the MXScrollView seems to fix that.
I'm not sure if this causes any side effect, though

**Comment by trungnguyen1791** [comment]
It's still happened event  "cancelsTouchesInView = false". 
Not all the time but almost...conflict between scroll down/up with collectionview's selection. 
Does anyone else have other solution for it?

**Comment by lexiaoyao20** [comment]
```
self.panGestureRecognizer.cancelsTouchesInView = YES;
```

I solved this problem.
