### ISSUE TITLE
Adding button to headerView doesn't work 

### ISSUE THREAD

**Issue by Jackson0111** [maxep/MXParallaxHeader#17]
Hey there! Great work! I was trying to add a button to the headerView to dismiss the view controller but the button can't pick up any gestures. Any idea what's going on?

**Comment by diego1199** [comment]
Have you try this:

UIImageView *headerView = //YOUR HEADER VIEW
`UIButton *dismissButton = [[UIButton alloc]initWithFrame:CGRectMake(8, 20, 30, 30)];
[dismissButton setImage:[UIImage imageNamed:@"dismissIcon"] forState:UIControlStateNormal];
 [dismissButton addTarget:self action:@selector(dismissView) forControlEvents:UIControlEventTouchUpInside];
 [headerView addSubview:dismissButton];`

**Comment by akkshay** [comment]
I tried the above solution and it didn't work. Anyone know if this issue has been resolved yet?

**Comment by Gantaios** [comment]
Hi any Resolved the issue can you tell me the solution @akkshay @diego1199 @Jackson0111

**Comment by hongzhou85** [comment]
In the header view controller (parallax header), try store the reference to the scrollview, collectionview or tableview controller. When I set the gesture recognizer, make sure you target the "parent", the view which set the parallax header and have the gesture recognizer function in the "parent". That way the touch will be send to parent and it will work.

`let tapGestureRecognizer = UITapGestureRecognizer(target:self.parent!, action:#selector(ParentViewController.functionGesture(_:)))

headerButton.userInteractionEnabled = true
headerButton.addGestureRecognizer(tapGestureRecognizer)`

**Comment by maxep** [comment]
You can refer to #36.
