### ISSUE TITLE
Troubles when add sections in UITableView

### ISSUE THREAD

**Issue by IgorBulyga** [maxep/MXParallaxHeader#24]
I have downloaded example project and just added sections in UITableView with simple title and when try scrolling section views freeze where they appear.

Any suggestions?

![simulator screen shot 26 2016 20 50 49](https://cloud.githubusercontent.com/assets/5319811/15584508/f34436be-238b-11e6-89d9-dfdab67ffcd1.png)
![simulator screen shot 26 2016 20 50 54](https://cloud.githubusercontent.com/assets/5319811/15584509/f3713b1e-238b-11e6-9e06-057b7e518505.png)

**Comment by txaiwieser** [comment]
Having the same problem here, any updates? did you managed to fixed?

**Comment by maxep** [comment]
I guess its because I treat UITableView as any UIScrollView. UITableView might need a specific category and the use of `tableHeaderView` property to work properly.

**Comment by maxep** [comment]
I've found a solution, could you please try it and reopen the issue if needed?

**Comment by IgorBulyga** [comment]
Now slide section is good, but if you set a minimum height for header that they will slide over header
![simulator screen shot 1 2016 19 57 16](https://cloud.githubusercontent.com/assets/5319811/15718441/58812fc8-283c-11e6-9543-98a7521a7262.png)

**Comment by IgorBulyga** [comment]
@maxep Thanks, all good!

**Comment by txaiwieser** [comment]
Awesome! Going to test as soon as i can! thanks

**Comment by kid9591** [comment]
@maxep @IgorBulyga 
I still got this problem with version 1.1.0. Could you help me, please?
I use Tableview inside UIViewController. And I configure the section header as follows:
```
func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
            return 40
    }
    
func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let label = UILabel(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 40))
        label.backgroundColor = .yellow
        label.text = "\(section)"
        return label
}
```

<img width="946" alt="Screen Shot 2020-04-25 at 16 26 05" src="https://user-images.githubusercontent.com/7839927/80276431-04084280-8713-11ea-8ce9-8ecc5017c2ac.png">
<img width="379" alt="Screen Shot 2020-04-25 at 16 28 29" src="https://user-images.githubusercontent.com/7839927/80276433-079bc980-8713-11ea-9be9-b4df59dc733d.png">
<img width="380" alt="Screen Shot 2020-04-25 at 16 28 35" src="https://user-images.githubusercontent.com/7839927/80276435-09fe2380-8713-11ea-9314-81d02ce8cb79.png">
<img width="378" alt="Screen Shot 2020-04-25 at 16 38 25" src="https://user-images.githubusercontent.com/7839927/80276462-34e87780-8713-11ea-9666-9198b8044487.png">
