### ISSUE TITLE
MXParallaxHeader's bug KVO

### ISSUE THREAD

**Issue by mixlan123** [maxep/MXParallaxHeader#30]
**\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <(null) 0x0> for the key path "contentOffset" from <MXParallaxView 0x149415ff0> because it is not registered as an observer.'

Class "MXParallaxView",remove observer wrong,when dealloc  <Object-C>

**Comment by isaced** [comment]
same question.

**Comment by maxep** [comment]
see #28
