### ISSUE TITLE
NavBar Height top constraint

### ISSUE THREAD

**Issue by violabg** [maxep/MXParallaxHeader#34]
Is there a way to take into account the navbar height when setting the parallaxHeader.
What I mean is to have the parallaxHeader top constraint start at the NavBar bottom

**Comment by maxep** [comment]
Do you mean by embed the MXScrollViewController in a nav controller?
Otherwise you can set the top constraint of your scrollview at the bottom of the navbar.

**Comment by stoosepp** [comment]
I'm having the same issue:( Top constraints on the scrollview and my added tableview (as contentView) are the size of the navbar, making gaps. Setting the navbar to opaque gets rid of the gaps, but moves the MXScrollview all the way to the top and my headerView is now covered up.

Side Question: Is it possible to interact with my headerView? I embedded a VC that has user interaction, but they don't seem to be working:(

Thanks for the help!
