### ISSUE TITLE
Disabling the stick effect on the header

### ISSUE THREAD

**Issue by wonathanjong** [maxep/MXParallaxHeader#35]
Where in the code can I disable the automatic closing of the header so that I can use MXParallaxHeader as just a regular header view that moves in sync with the scrollview offset with the still zoom in effect when pulling down?

**Comment by maxep** [comment]
This should be possible by setting the same value to `height` and `minimumHeight`. But your question has highlighted an bug while using the parallax header in a table view : The `minimumHeight` is added to the `height`, which is not the expected behavior. This is due to the top inset adjustment.
