### ISSUE TITLE
Button click method not working

### ISSUE THREAD

**Issue by Gantaios** [maxep/MXParallaxHeader#36]
Hi thanks for your great control just want to add gestures to the headerviw how can we achieve that please tell me

**Comment by hongzhou85** [comment]
Same i cannot detect any gestures or IBAction in the parallax header. How do intercept the touch?

**Comment by jj-12** [comment]
Same here.  This would be an awesome thing to know.  Thanks!

**Comment by hongzhou85** [comment]
I have achieved it by storing a reference of the tableViewController or scrollViewController or collectionViewController in the headerView. Then set the buttons' touchGestureRecognizer target to your reference and have the function in there to handle the action. It should works that way.

**Comment by hongzhou85** [comment]
For the header:

```
class HeaderView : UIVIewController {
  @IBOutlet weak var button : UIButton!
  var parent: UIViewController?  // Usually your tableview/scrollview/collectionview

  override viewDidLoad() {
    let tapGestureRecognizer = UITapGestureRecognizer(target:self.parent!, action:#selector(ParentViewCollection.actionGesture(_:)))
        button.userInteractionEnabled = true
        button.addGestureRecognizer(tapGestureRecognizer)
  }
}
```

For the "parent":

```
class ParentViewController : UIViewController {
   let header : HeaderView = HeaderView()

   override viewDidLoad() {
        header.parent = self
        self.collectionView!.parallaxHeader.view = header.view
        self.collectionView!.parallaxHeader.height = headerHeight
        self.collectionView!.parallaxHeader.mode = MXParallaxHeaderMode.Fill
        self.collectionView!.parallaxHeader.minimumHeight = 0
   }

   func actionGesture(sender : UIGestureRecognizer) {
        // here you can do what you want with the button
    }
}
```

**Comment by maxep** [comment]
This is a good approach @hongzhou85. Instead of setting a `parent`property, you can create a delegate and call that delegate on gesture.
Another approach would be to create a floating view in your view controller from storyboard, then to attach this floating view to your parallax header. This would allow you to trigger segues directly from your header view.

**Comment by jj-12** [comment]
Great, the floating view seems to work pretty well.  Thanks guys!

**Comment by AmruthaMurthy1512** [comment]
> Great, the floating view seems to work pretty well. Thanks guys!

Any code snippet how you added a floating view. My requirement is that I need to add back button on Top of Parallex header view.

**Comment by AmruthaMurthy1512** [comment]
> This is a good approach @hongzhou85. Instead of setting a `parent`property, you can create a delegate and call that delegate on gesture.
> Another approach would be to create a floating view in your view controller from storyboard, then to attach this floating view to your parallax header. This would allow you to trigger segues directly from your header view.

Any code snippet how you added a floating view. My requirement is that I need to add back button on Top of Parallex header view.
