### ISSUE TITLE
MXParallaxHeader with transparant navigation and status bar

### ISSUE THREAD

**Issue by edwardmp** [maxep/MXParallaxHeader#37]
Thank you for making this plugin. It's awesome.

I have a table view with a transparant navigation and statusbar and I want the top of the parallax view to be at x = 0 (top of statusbar).

Previously when I just had a plain table header view, this worked OK. Now with MXParallaxHeader it's a bit different. Somehow I can't achieve the same behavior. See screenshot as to where it stops. The blue part is the top of the table view header. You can see the back arrow of the navigation bar halfway. There is whitespace between the parallax view top and the status bar area.
I do note that by scrolling and flicking I sometimes can actually get the parallax in the right position!

![simulator screen shot 6 aug 2016 00 42 27](https://cloud.githubusercontent.com/assets/1686739/17452383/0c49ef94-5b6f-11e6-8775-f5086b96c1ba.png)

Here's a bit of my code:

```
    self.navigationController.navigationBar.translucent = YES;

    // make status bar + navbar translucent so it can show table header background image
    [self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
    self.navigationController.navigationBar.shadowImage = [UIImage new];

    self.navigationController.toolbarHidden = FALSE;

    [self.navigationController.navigationBar setBackgroundColor:[UIColor clearColor]];

    // place table header view under statusbar by offsetting the table view
    CGFloat statusBarHeight = [[UIApplication sharedApplication] statusBarFrame].size.height;
    self.tableView.contentInset = UIEdgeInsetsMake(statusBarHeight, 0, 0, 0);

    // Parallax Header
    self.tableView.parallaxHeader.view = self.flightDetailHeadView;
    self.tableView.parallaxHeader.height = 280.0f;
    self.tableView.parallaxHeader.mode = MXParallaxHeaderModeTopFill;
    self.tableView.parallaxHeader.minimumHeight = 100.0f;

```

**Comment by edwardmp** [comment]
Issue was with the view itself, not caused by MXParallaxHeader. Sorry, I will close this issue.

**Comment by habibmohammadidev** [comment]
can u tell me how to solve this problem? i faced the same problem as you :(
