### ISSUE TITLE
Bug: on tableView(UITableViewStyleGrouped),section 's header will cover ParallaxHeader

### ISSUE THREAD

**Issue by 12207480** [maxep/MXParallaxHeader#38]
![image](https://cloud.githubusercontent.com/assets/6346030/17616147/6ba34b76-60a5-11e6-8b1f-7b6012c22f4a.png)

solution：
parallaxHeader.contentView.layer.zPosition = 1;

**Comment by sebayaki** [comment]
@12207480 Thanks for sharing your solution. I was struggling with the same issue for a while.
