### ISSUE TITLE
Input field become first responder makes content offset change

### ISSUE THREAD

**Issue by rordeix** [maxep/MXParallaxHeader#39]
I'm using the parallax header as a header for a collection view, the idea is to have a header, collapsable to certain point, with a search field and other stuff. The thing is when the user click or the search field becomes first responder, the content offset of the header seems to be changed and makes the collection view scrolls down. I'm not sure if is a problem of the library, but just wanted to let you know. I'm going to get it working by myself.

**Comment by trungnguyen1791** [comment]
@rordeix Did the offset's change make your collection view's frame move down a bit?
Can you share something about your working on it? 
Thanks

**Comment by gerasumit** [comment]
I am facing the same issue but with UITableView.

**Comment by meghs91** [comment]
@rordeix do you have any suggestion on how to fix this issue?

**Comment by gsoykan** [comment]
I am also facing the same issue with a collection view. Any help would be much appreciated.

**Comment by bhargavsejpalindianic** [comment]
Same issue
