### ISSUE TITLE
Bug when cells don't fill the screen

### ISSUE THREAD

**Issue by Ricardo1980** [maxep/MXParallaxHeader#43]
If we modify the sample project to return less cells than the size of screen, for example 2, and we setup a minimumHeight, like:
self.scrollView.parallaxHeader.minimumHeight = 100;

Then there is a weird behaviour in the header, see video.
At the moment I didn't have time to research, will do that later.

![bug header mov](https://cloud.githubusercontent.com/assets/738681/18280985/05fced92-7453-11e6-88b9-d2aeef694805.gif)

**Comment by maxep** [comment]
Wow yes its weird.. maybe its related to #41, did you try with the latest code ?

**Comment by Ricardo1980** [comment]
I tried the last code right now and it is even worse, because it is happening from the beginning, without modifying the sample code. See attached video.

![header mov](https://cloud.githubusercontent.com/assets/738681/18305691/a3d66dda-74e0-11e6-97d2-0fe56ba5569f.gif)

**Comment by jj-12** [comment]
I'm seeing the same issue with the latest code.  It only happens when the table does not have enough cells to fill the whole screen for me though.
