### ISSUE TITLE
Bug regarding moving the header all the time to the front.

### ISSUE THREAD

**Issue by Ricardo1980** [maxep/MXParallaxHeader#44]
If I add  a view to the tableView (which is a scrollView), it is always behind the header, even if I force it moving to the front.

In file MXParallaxView.m, method layoutContentView, I see the lines:
        // Keep table header view over sections
        [self.scrollView bringSubviewToFront:self.contentView.superview];

If I comment that line, it is working properly, even with a table that has sections. 
So, I don't understand the purpose of that line.
Can we remove it or is there a edge case I don't see?
Thanks.

**Comment by maxep** [comment]
In my tests, the sections view scrolls on top of the header. Did you try on ios10?
