### ISSUE TITLE
Unrecognized selector sent to instance

### ISSUE THREAD

**Issue by bitomule** [maxep/MXParallaxHeader#48]
Installed MXParallaxHeader from carthage and I get this error:

`[UITableView parallaxHeader]: unrecognized selector sent to instance 0x7ff0ad872200`

Cocoapods version seems to be ok

**Comment by maxep** [comment]
Did you add the framework to the `Embedded Binaries` of your app?

**Comment by bitomule** [comment]
Ups, that was the issue. Sorry
