### ISSUE TITLE
Parallax header doesn't extend below status bar in NavigationController

### ISSUE THREAD

**Issue by MasterCarl** [maxep/MXParallaxHeader#53]
I embedded the Scroll View Example (Swift example) in a NavigationController with its Navigation Bar hidden. With this setup, the header view sits just under the status bar, but doesn't extend below it. However, the scroll view content is still visible at the top, as can be seen in the picture below.

![simulator screen shot 20 dec 2016 18 28 34](https://cloud.githubusercontent.com/assets/6067572/21361159/1c14ba82-c6e3-11e6-9020-ff4ff18ac4f4.png)
<img width="531" alt="storyboard" src="https://cloud.githubusercontent.com/assets/6067572/21361184/2f9c7dec-c6e3-11e6-9f68-97d1f68fc2f7.png">

**Comment by MasterCarl** [comment]
I solved the problem by setting `automaticallyAdjustsScrollViewInsets = false` in my ViewController's `viewDidLoad` function. Still, it might be worth mentioning this in the documentation.

**Comment by paul-brighter** [comment]
@MasterCarl you'are awesome!
