### ISSUE TITLE
off bounce of MXScrollView

### ISSUE THREAD

**Issue by ghost** [maxep/MXParallaxHeader#54]
I have tried from storyboard to turn off the bounce as we usually do, and also tried programmatically like these :

1)  profileDetailScrollView.bounces = false

2) func scrollViewDidScroll(scrollView: UIScrollView) {
        NSLog("progress %f", scrollView.parallaxHeader.progress)
        
        if scrollView.contentOffset.y < 0 {
            scrollView.contentOffset.y = 0
        }
    }

But these solutions are not working, please help.

**Comment by maxep** [comment]
I cannot reproduce.. If i set `bounces` to false on the tableView of the `UIScrollViewExample`, it well stops bouncing.
