### ISSUE TITLE
Comportement étrange lors du scroll

### ISSUE THREAD

**Issue by Aurazion** [maxep/MXParallaxHeader#57]
Bonjour @maxep,
J'utilise ta classe pour mon projet et j'en suis très satisfait. Cependant il y a un comportement étrange qui se retrouve également dans la démo (par exemple sur l'onglet MXScrollViewController). Si on scroll légèrement vers le bas et qu'on arrête le scroll avant que le header soit entièrement caché, impossible de scroller vers le haut avant de scroller un peu plus vers le bas pour "débloquer" le scroll vers le haut.
J'espère que mon explication est assez claire. Je n'arrive pas à voir d'où cela peut venir... 

Merci d'avance pour ton aide.

**Comment by maxep** [comment]
Hi @Aurazion 
Please write your issue in english so other developers can understand and help. I've seen this behavior, but I havent found a solution yet, I'm looking at it...

**Comment by Aurazion** [comment]
It works thank you ! (And sorry for my first message in french)
