### ISSUE TITLE
Issue with sticking to minimumHeight

### ISSUE THREAD

**Issue by ivanbarisic05** [maxep/MXParallaxHeader#59]
Hi there, thanks for your great lib. I have an issue where I try to disable MXParallaxHeader to stick to minimumHeight. It's like this, header is full screen image and when I scroll it down I get "stuck" on minimumHeight. Can you help me to avoid this kind of behaviour?

This is my implementation:

`scrollView.parallaxHeader.view = header`
`scrollView.parallaxHeader.minimumHeight = 0`
`scrollView.parallaxHeader.height = UIScreen.main.bounds.height`
`scrollView.parallaxHeader.mode = MXParallaxHeaderMode.center`
`scrollView.parallaxHeader.delegate = self`

**Comment by maxep** [comment]
Hi, I'm sorry, I'm not sure to understand your issue. By setting `scrollView.parallaxHeader.minimumHeight = 0` the header do not desappear when you scroll up ?
What is you scrollview's content insets?

**Comment by ibarisic05** [comment]
Hi @maxep, thanks for reply. I had issue when i set configuration like described on collection view. Problem was when I start scrolling up, screen stops when parallax header reaches offset that should get him outside the screen. Any way, I have solved this by creating my custom solution for the header. Thanks

**Comment by timotheeduran** [comment]
Hi, I have the same issue, anyone knows how to fix it ? :)

**Comment by axmav** [comment]
+1
