### ISSUE TITLE
Fill Mode Gives an Error

### ISSUE THREAD

**Issue by Mwiti** [maxep/MXParallaxHeader#6]
scrollView.parallaxHeader.mode = MXParallaxHeaderModeFill -> this line gives me the following error: 

Use of unresolved identifier 'MXParallaxHeaderModeFill'

but i can cmd+click on the MXParallaxHeaderModeFill and still get the page where it's defined. am i doing something wrong everything else is working but i can't work without this line because the header image is squashed when i run. Please help. Danke!

**Comment by Mwiti** [comment]
nvm. got it. .Fill is the right one...  _amature problems_ :)

**Comment by maxep** [comment]
No worries :+1:
