### ISSUE TITLE
resize header height

### ISSUE THREAD

**Issue by CavalcanteLeo** [maxep/MXParallaxHeader#60]
My header loads with a specific height, then I fetch the user data on server and load all informations about the user.

I need to change the header size after all informations are ready.

I tried to use `self.segmentedPager.parallaxHeader.height = CGRectGetHeight(headerBoxView.bounds);` but didn't work

the `CGRectGetHeight(headerBoxView.bounds` returns the right height, but the header doesn't change
```objective-c
[headerBoxView setNeedsLayout];
self.segmentedPager.parallaxHeader.height = CGRectGetHeight(headerBoxView.bounds);
[self.segmentedPager reloadData];
[self.segmentedPager layoutIfNeeded];
[self.view layoutIfNeeded];
```

**Comment by ghost** [comment]
any updates about this issue?

**Comment by tschmitz** [comment]
@CavalcanteLeo Did you find a solution to this issue? I'm having the same problem.

**Comment by tiwari1amrit** [comment]
Did anybody find a solution of this issue?

**Comment by trmquang** [comment]
I'm having the same problem too

**Comment by cgarg** [comment]
Same problem. @maxep Is there any solution or hack for this? TIA 🙏🏻

**Comment by sseno** [comment]
Anyone knows how to fix it ? :')
