### ISSUE TITLE
With multiple scrolling it calling parallaxHeader scrollview delegate method not handle properly 

### ISSUE THREAD

**Issue by TheCodeTalker** [maxep/MXParallaxHeader#61]
[(MXScrollView*)scrollView scrollViewDidScroll:scrollView];
    if ([self.delegate respondsToSelector:_cmd]) {
        [self.delegate scrollViewDidScroll:scrollView];
    }
i have a table view inside every row one one collection view present and horizontal can scroll every time scroll the parallaxHeader also effecting because of this  i facing problem . how i will solve this problem help me???? @maxep 
thanks

**Comment by maxep** [comment]
You can try to prevent the `MXScrollView` from scrolling with your collection views by implement the delegate method `scrollView:shouldScrollWithSubView:`. By returning NO, the MXScrollView wont move with the subview.
Hope this help
