### ISSUE TITLE
Refresh the controllers inside mxparallaxheader when some data change

### ISSUE THREAD

**Issue by hananahmad** [maxep/MXParallaxHeader#63]
I have implemented the MXParallaxHeader using storyboard and I need to refresh my tableview or collectionview with updated datasource but I didn't find any controller reference like any delegate method which gives us the selected controller so that I can call that methods please help me to fix this thanks

**Comment by brycelund** [comment]
I was also unable to find any pull to refresh option that didn't completely wreck my Parallax header. My solution, while a little hacky, worked for me. 


`var refreshready:Bool = true`

```
   func parallaxHeaderDidScroll(_ parallaxHeader: MXParallaxHeader) {
        if(parallaxHeader.progress > 1.5 && refreshready){
            refreshready = false
            refreshData()
        }
    }
```


```
func refreshData(){
        
        print("Refresh Started")
        
       // Refresh your data
       // Show an activity Spinner

            self.refreshready = true

    }
```
