### ISSUE TITLE
What the proper way of remove the ParallaxHeader?

### ISSUE THREAD

**Issue by lingzlu** [maxep/MXParallaxHeader#64]
In my tableview, there's a setting where user can toggle to disable the parallaxHeader. Is there a property for that?

Currently, I'm doing 

```
tableView.parallaxHeader.view = nil
tableView.parallaxHeader.height = 0
tableView.parallaxHeader.minimumHeight = 0
```

This hide the parallaxHeader, but when I pull the tableView and it bounce, I'm still seeing UIImageView I set before. This feels wrong.

`tableView.parallaxHeader.view = imageView`

**Comment by pplant** [comment]
+1

**Comment by yjosephides** [comment]
Maybe replace with an empty UIView()?
