### ISSUE TITLE
Using MXParallaxHeader in UITableView with headers

### ISSUE THREAD

**Issue by iDevo** [maxep/MXParallaxHeader#65]
Hi there, 
I'd like to use MXParallaxHeader in my UITableView, which worked great until I started adding section headers. 
The section header anchor point seems to be at the end of the ParallaxHeader, so the section headers stop there. Moreover the passed headers are moving above the HeaderView. 

Is there a way to change this behaviour or a workaround?

Thanks in advance! 

![mxissue](https://cloud.githubusercontent.com/assets/8428287/24578796/c86f37e4-16e8-11e7-8857-805a99d36d63.gif)

**Comment by jyounus** [comment]
I'm after the same functionality. Did you manage to solve this @iDevo?

**Comment by maxep** [comment]
The support of table view with sections have been removed because it removes the header touch on upward position, please refer to #40. As a workaround, you can embed your view controller in a `MXScrollViewController`, I havent tried yet but it should work.

**Comment by Ilya-Pak** [comment]
I did manage to make it work right  by creating a scrollview and adding to it MXParallaxView and UITableView. But what I've notice is that when user start scrolling it accidently recongnize gesture as tap not swipe and calls actions like didSelectRow:
I think it's because both delegates of scrollview and tableview are hinder each other.
Do you have any ideas how to fix it?

And thanks a lot for this project! Great job!

**Comment by HoanPH** [comment]
You have the same issue with me. 
In my case, I change tableview style plain to group. After that, set background for tableview and set height for header and footer in section in tableview delegate.
Hope this help.

**Comment by HoanPH** [comment]
I have the same issue with section header.
In my case, i change table view style plain to group. After that, set heightForHeaderInSection, heightForFooterInSection in tableview delegate. The section header will not sticky when scroll.
Hope this help!

**Comment by leithonenglish** [comment]
@maxep How would u go about embedding the viewController in in the MxScrollViewController

**Comment by TrungTuyenTran** [comment]
I create a MXScrollView and put collectionView into MXScrollView. Set scrollView.parallaxHeader.view is "babysuccess" UIImageView . It can resolved this problem . But It have a new problem, when I scroll to bottom of collectionView , I can keep scroll down although I set bounces for scrollView and collectionView is true.

**Comment by janeshsutharios** [comment]
i Solved by         contentView.layer.zPosition = 1

**Comment by minhchau273** [comment]
@janeshsutharios Which `contentView` did you mention above?

**Comment by jeremypiednoel** [comment]
> @janeshsutharios Which `contentView` did you mention above?

`tableView.parallaxHeader.contentView.layer.zPosition = 1`

**Comment by janeshsutharios** [comment]
@jeremypiednoel @minhchau273  in `MXParallaxHeader/MXParallaxHeader.m` `- (void)layoutContentView method` . write objc c equivalent code ( `tableView.parallaxHeader.contentView.layer.zPosition = 1`) at bottom of function.
