### ISSUE TITLE
Like parallax

### ISSUE THREAD

**Issue by vre142** [maxep/MXParallaxHeader#71]
![photo_2017-06-27_12-01-07](https://user-images.githubusercontent.com/11377075/27575854-57368e38-5b30-11e7-956f-e7653c8bfb44.jpg)
![photo_2017-06-27_12-01-16](https://user-images.githubusercontent.com/11377075/27575853-57304a0a-5b30-11e7-9d73-4513d3135964.jpg)
Hi,
Thank You for your great library. can you explain how can i do some thing like these pictures with your library?
Thanks

**Comment by maxep** [comment]
I suggest to use stackoverflow for this kind of question.
