### ISSUE TITLE
Parallax doesn't work in release mode

### ISSUE THREAD

**Issue by Asbelita** [maxep/MXParallaxHeader#79]
I have installed and run MXParallaxHeader to my project, apparently all was working good until I archived my project and could see that this doesn't appear. I don't have any idea about was going on here. I did a test with example project, this works fine in debug and release. Somebody knows how fix this?

**Comment by hyd00** [comment]
Same issue! Pleae help!

**Comment by billidani7** [comment]
Have you found any solution?
