### ISSUE TITLE
Limit "Pull down" length?

### ISSUE THREAD

**Issue by thephatp** [maxep/MXParallaxHeader#80]
When viewing the parallax header, I would like to limit how far the user can pull down the header. I couldn't find a setting that allows this. Is it possible now, or would it require changes + a pull request? If a pull request, is this project maintained anymore?

**Comment by Tim77277** [comment]
Have you tried to set minimumHeight instead of limit how far the user can pull down? I think two of them are correlated.

**Comment by j796160836** [comment]
I think the original problem is where can set the scrolling bounce off?
