### ISSUE TITLE
iOS 11 glitch with MXScrollViewController

### ISSUE THREAD

**Issue by Aurazion** [maxep/MXParallaxHeader#82]
Hi,
When I build my project with Xcode 9 / iOS11, a glitch appear when I scroll it. The same with Xcode 8 / iOS10 works great.
This issue occur whith MXScrollViewController.

With the MXScrollViewController demo, there is also a problem with the UIWebView when you scroll to top. Could you check please ?

Don't hesitate to contact me.

Thanks!

**Comment by Aurazion** [comment]
The problem occur when I scroll down and then scroll to top (see the screenshot attached).

Thanks @maxep 

![ios11](https://user-images.githubusercontent.com/6509814/30750723-89e64316-9fb7-11e7-86c1-91090dfab54b.jpg)

**Comment by Nexmind** [comment]
Do you tried the new property of tableView available on iOS 11 ? 
`contentInsetAdjustmentBehavior`

Try something like that
`
tableView.contentInsetAdjustmentBehavior = .never
`

**Comment by Nexmind** [comment]
There are a similar problem with parallax header using tableview. 

For tableview, there are a new property `contentInsetAdjustmentBehavior` that you can put to `.never`and it solve the problem. 

Maybe you can check if there are something similar for scrollview. It should be exist.

Something like that `scrollview.contentInsetAdjustmentBehavior = .never`

**Comment by Aurazion** [comment]
I will try this and keep you informed, thanks @Nexmind !

**Comment by Aurazion** [comment]
@Nexmind It solve my problem thanks ! But now I've a "padding" on the top of the scrollview ? Did you know how I can delete it ?
Thanks !

![ios11_2](https://user-images.githubusercontent.com/6509814/30751824-d2038138-9fba-11e7-905d-8e85c7ca8b92.jpg)

**Comment by Nexmind** [comment]
I had similar issue on iPhone X only with some tableview in my app. 
I have no real solution for the moment. What i made as quick win option is to substract padding height in my top constraint if the phone was an iPhone X.

    if DeviceType.IS_IPHONE_X {
           self.cstTopTableView.constant = self.cstTopTableView.constant - 25
    }

**Comment by Aurazion** [comment]
Ok it's just a problem with my constraints ... It now works great ! Thanks again @Nexmind ! I will try your solution for the iPhone X :-)

**Comment by maxep** [comment]
Thanks @Aurazion and @Nexmind 
I'm struggling with this new content inset adjusment behavior... 
@Aurazion have you try to uncheck the content inset adjustment of your view controller?
