### ISSUE TITLE
move MXScrollView to top programmatically

### ISSUE THREAD

**Issue by shaharukhs** [maxep/MXParallaxHeader#83]
I have some textfields on MXScrollView when I select bottom textfield it hides by keyboard so I need to move MXScrollView to top with progress value 0.

How can I achieve this?

Thank you.

**Comment by brunohorta82** [comment]
i have this issue too

**Comment by shaharukhs** [comment]
Following code work for me hope it's helps you

`self.mxScrollView.contentOffset = CGPoint(x: 0.0, y: 0.0)`

and for restore to its position 

`self.mxScrollView.contentOffset = CGPoint(x: 0.0, y: -150.0) // my parallax header height is 150`
