### ISSUE TITLE
Floating Section Header not scrolling with tableView after using MXParallaxHeader for the tableHeaderView

### ISSUE THREAD

**Issue by Tim77277** [maxep/MXParallaxHeader#84]
So I am facing this problem on my project. Somehow we must use UITableView with Plain Style and then dynamically adding table section header in to the tableView. And for the TableHeaderView of course I am using MXParallaxHeader. However, when I scroll the tableView up, my section header view got stock at the origin position while all cells are scrolling up. It is a very weird behavior I never seen before.  I know #65 asked the same question but there is no a correct response. Please help. Thank you

**Comment by Tim77277** [comment]
So I tried #65 solution again and it worked. Basically what you should do to make UITableView Section Header works with MXParallaHeader is to **add UITableView into MXScrollView,  assign your MXParallaxHeader (View) to the scrollView.parallaheader.view**. And then **set the correct scrollView.contentSize** otherwise it won't be scrollable. This works well for my project, but the **upcoming issue is that scrollView.parallaheader.minimumHeight doesn't work** in this case. If someone know the solution, please share. Thanks

**Comment by TrungTuyenTran** [comment]
@Tim77277  I did that like you say , it worked . But It have a problem, when I scroll the list to the bottom , I can't keep scroll down although I set scrollView.bounces = true and collectionView.bounces = true. Did you get this problem?

**Comment by Tim77277** [comment]
@TrungTuyenTran In my case, tableview was not scrollable until I set up the correct scrollView.contentSize and set collectionView and scrollView bounces = true, like you mentioned. But I was able to scroll to all the way down. Do you want to double check if your contentSize is correct?

**Comment by TrungTuyenTran** [comment]
@Tim77277  How is correct ? How did you set contentsize for your tableview . I set scrollView.contentSize = collectionView.contentSize. Is that right? . In my case , collectionview also can scroll , but when scroll to bottom , you can't keep scroll down . I mean It stop in bottom at collectionView , you can't continue to scroll down.

**Comment by gaqraa** [comment]
Same issue , any update

> @Tim77277 I did that like you say , it worked . But It have a problem, when I scroll the list to the bottom , I can't keep scroll down although I set scrollView.bounces = true and collectionView.bounces = true. Did you get this problem?

**Comment by e-nicolas** [comment]
> @Tim77277 I did that like you say , it worked . But It have a problem, when I scroll the list to the bottom , I can't keep scroll down although I set scrollView.bounces = true and collectionView.bounces = true. Did you get this problem?

Same problem here

**Comment by e-nicolas** [comment]
> @Tim77277 I did that like you say , it worked . But It have a problem, when I scroll the list to the bottom , I can't keep scroll down although I set scrollView.bounces = true and collectionView.bounces = true. Did you get this problem?

Same problem here
