### ISSUE TITLE
MinimumHeight doesn't work in scrollView

### ISSUE THREAD

**Issue by Tim77277** [maxep/MXParallaxHeader#85]
I have a tableView embedded in a MXScrollView. I need to have a minimum height for the MXParallaxHeader. But the below code doesn't work

`scrollView.parallaxHeader.minimumHeight = 60`

No matter what height I set, it always scroll to top without minimum height.
Any Idea how to solve it? 

Thanks for the great library

**Comment by toddgower-hiatus** [comment]
I was having the same issue in the sample project for Swift until I realized that the `minimumHeight` is set both in `viewDidLoad()` and `viewDidAppear()` in the `UIScrollView` example
