### ISSUE TITLE
Issue with HTML Inputs on WKWebview 

### ISSUE THREAD

**Issue by CaseJnr** [maxep/MXParallaxHeader#89]
Hi and thanks for the plugin, it's awesome. I am having issues using it with a WKWebview. The html input elements become hard to select when the ParallaxHeader is active. Its also difficult to select hyperlinks. Any ideas what might be causing the issue?

**Comment by lexiaoyao20** [comment]
@CaseJnr 
I have open a pull request about support `WKWebView`。 Maybe help you.
https://github.com/maxep/MXParallaxHeader/pull/96

**Comment by maxep** [comment]
PR #96 has been merged
