### ISSUE TITLE
UICollectionView dragging is not smooth

### ISSUE THREAD

**Issue by unash** [maxep/MXParallaxHeader#9]
Then MXScroll content is a UICollectionView.
I have dragged the collectionView reducing the header space.
And  I drag the collectionView **downwards** , sometimes my action doesn't work.
It is frozen except I drag the collection view **upwards** first.

**Comment by unash** [comment]
It appear in the third page of the demo.
I suppose is was caused by nesting of scrollViews.

**Comment by maxep** [comment]
Do you have constraints in your UICollectionViewCells?

**Comment by unash** [comment]
No, I use frame to layout. 
It seems not collection view but the nesting of scroll view causes the dragging stuck.
At the third tab of your demo, drag the web view upwards, end dragging before reaching screen top.
Touch the screen then and drag downwards. Try several time and you may find it.
And touch again, it will turns to be OK.
It is tiny and leaving it is also fine.
I really appreciate the framework and it helps me a lot.

**Comment by arsonik** [comment]
+1

**Comment by JoshyMW** [comment]
I am also finding this with a nested UITableView and the cells do have constraints. This only affects scrolling up and at certain positions through the scroll. However the table view cells have editing styles and the swipe gesture, I think, may be interfering.

**Comment by JoshyMW** [comment]
Its not the swipe gesture thats interfering and testing out nested scroll views without MXParallelHeader works fine, however it looks like this may be related to having bounce enabled when one of the nested tableviews reaches the end. This is quite a high priority issue for us so any help would be greatly appreciated.

**Comment by JannyKul** [comment]
+1

**Comment by trungnguyen1791** [comment]
+1. I faced the same problem as well.
And sometimes, pan gestures seem conflicted with collectionview selection gesture too.

**Comment by hananahmad** [comment]
@maxep  Please help me out I have collectionView in one tab and when I scroll my collection view its didSelectItemAtIndexPath calls instead of scrolling infact I am not taping on any cell I am scrolling as I have not faced that kind of problem before please respond asap thanks  .

**Comment by nthtrung09it** [comment]
+1

**Comment by nthtrung09it** [comment]
> @maxep Please help me out I have collectionView in one tab and when I scroll my collection view its didSelectItemAtIndexPath calls instead of scrolling infact I am not taping on any cell I am scrolling as I have not faced that kind of problem before please respond asap thanks .

Did you find a solution for that issue?
