### ISSUE TITLE
Strange bump when updating tableView on cell height

### ISSUE THREAD

**Issue by Nexmind** [maxep/MXParallaxHeader#93]
Hello,

In a little app, i set the number of line of labels contained in my cell when touching it, and updates my tableView. 

In a certain range of scrolling, i have some strange bump. The intensity of the bump depend of where i am in the range. 

See the gif attached to a better comprehension.

This is the method i call when updating my tableView:
```Swift
func showOrHideMoreText() {
    let angle: CGFloat = self.isExpanded ? (.pi / 2) * -1 : .pi / 2
    self.labelValue.numberOfLines = self.isExpanded ? 3 : 0
    UIView.animate(withDuration: 0.3, animations: {
        self.chevron.transform = self.chevron.transform.rotated(by: angle)
    })
    self.isExpanded = !self.isExpanded
}
```

And i simply use this in my didSelectRow:
```Swift
   tableView.beginUpdates()
   cell.showOrHideMoreText()
   tableView.endUpdates()
```
iOS 11.3 and iPhone 7

GIF:
![expandedproblem](https://user-images.githubusercontent.com/16007775/40135575-f8f7273c-5945-11e8-9738-c51e26f75104.gif)

**Comment by hendyevan** [comment]
Hi @Nexmind , im getting this strange behaviour too when updating table view.
Im temporary fixing this problem using `tableView.scrollToRow(at: indexPath, at: .bottom, animated: true)`
