### ISSUE TITLE
Pull to refresh not working

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXParallaxHeader#97]
Hi @maxep 
Pull to refresh is not working along with parallax header.
It tried setting bounce to false for my tableview which set the pull to refresh disabled.

Please help how can we solve this.

**Comment by arturdev** [comment]
@hardikamal I had the same problem, so I made my own library: 
https://github.com/arturdev/AMRefresher 

Which works great with my fork: 
https://github.com/arturdev/MXParallaxHeader

**Comment by hardikamal** [comment]
@arturdev Where is the implementation of AMRefresher with ParallaxHeader?

**Comment by ChristopherSamso** [comment]
@arturdev Where is the implementation of AMRefresher with ParallaxHeader?

**Comment by arturdev** [comment]
@hardikamal @ChristopherSamso There is no example of that. 
You just need to use my [fork ](https://github.com/arturdev/MXParallaxHeader) and use [this refresher](https://github.com/arturdev/AMRefresher)

**Comment by djmunish** [comment]
I cloned you fork, now how to use this refresher? Simple install via pod and implement it?
